#开发缓解
#开发服务器配置
server:
  port: 25560

#spring开发环境
spring:
  #开发数据库连接配置
  datasource:
    #url
    url: jdbc:mysql://116.23.155.164:11000/dev?serverTimezone=Asia/Shanghai&useSSL=false
    #名字
    username: root
    #密码
    password: 970106
    #连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver