#spring-boot项目主配置
spring:
  profiles:
    #配置当前环境 dev为开发环境
    active: dev
  application:
    #项目名
    name: project-template

#mybatis配置
mybatis:
  # xml存放路径
  mapper-locations: classpath:mapper/**/*-mapper.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true